# Generated by Django 4.2.7 on 2023-12-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_tasks', to='app.employee'),
        ),
    ]
