# Generated by Django 4.2.7 on 2023-12-08 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_todo_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
